# DATA CLEANING CHALLENGE 

*Executed By Adeyemi Oluwaseyi*

[Click here to check my Linkedin profile](https://www.linkedin.com/in/oluwaseyi-adeyemi-33b1ab197/)

[Twitter link](https://twitter.com/AmLegendseyi)

## Introduction 

DataCleaning challenge provides an opportunity for every Data Analyst at all levels of expertise (beginner, intermediate,  or even expert) to build a portfolio-worthy project that can be shared with recruiters.

The challenge also provides an avenue for Data Analysts to meet with fellow learners and build a great network.   

#### What to look out for when cleaning your data

 - Incorrect data types
 - Null entries
 - Missing values
 - Duplicate entries
 - Errors in spellings and values
 - Wrong calculations across rows and columns
 - Irrelevant data 
 - Outliers 

First, importing the necessary libraries required to perform the above operations

 - ## Importing Libraries

In [2]:
#Importing Libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
# read the data set into dataframe using the pandas library
pd.set_option('display.max_columns', None)
data = pd.read_csv('fifa21 raw data v2.csv', skip_blank_lines=True, low_memory=False,)


Lets view our dataframe and observe the data

 - ## Observing The Dataset

## Some of the columns are abbreviated the meaning can be found [here](dataset_dictionary.txt). 

In [4]:
# previewing the first 10 rows of the dataset
data.head(10)

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   
5  188545     R. Lewandowski            Robert Lewandowski   
6  209331           M. Salah                 Mohamed Salah   
7  212831            Alisson         Alisson Ramses Becker   
8  231747          K. Mbappé                 Kylian Mbappé   
9  192448      M. ter Stegen         Marc-André ter Stegen   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   
5  https://cdn.sofifa.com/players/188/545/21_60.png   
6  https://cdn.sofifa.com/players/209/331/21_60.png   
7  https://cdn.sofifa.com/players/212/831/21_60.png   
8  https://cdn.sofifa.com/players/231/747/21_60.png   
9  https://cdn.sofifa.com/players/192/448/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   
5  http://sofifa.com/player/188545/robert-lewando...      Poland   31    91   
6  http://sofifa.com/player/209331/mohamed-salah/...       Egypt   28    90   
7  http://sofifa.com/player/212831/alisson-ramses...      Brazil   27    90   
8  http://sofifa.com/player/231747/kylian-mbappe/...      France   21    90   
9  http://sofifa.com/player/192448/marc-andre-ter...     Germany   28    90   

   POT                         Club     Contract   Positions Height Weight  \
0   93         \n\n\n\nFC Barcelona  2004 ~ 2021  RW, ST, CF  170cm   72kg   
1   92             \n\n\n\nJuventus  2018 ~ 2022      ST, LW  187cm   83kg   
2   93      \n\n\n\nAtlético Madrid  2014 ~ 2023          GK  188cm   87kg   
3   91      \n\n\n\nManchester City  2015 ~ 2023     CAM, CM  181cm   70kg   
4   91  \n\n\n\nParis Saint-Germain  2017 ~ 2022     LW, CAM  175cm   68kg   
5   91    \n\n\n\nFC Bayern München  2014 ~ 2023          ST  184cm   80kg   
6   90            \n\n\n\nLiverpool  2017 ~ 2023          RW  175cm   71kg   
7   91            \n\n\n\nLiverpool  2018 ~ 2024          GK  191cm   91kg   
8   95  \n\n\n\nParis Saint-Germain  2018 ~ 2022  ST, LW, RW  178cm   73kg   
9   93         \n\n\n\nFC Barcelona  2014 ~ 2022          GK  187cm   85kg   

  Preferred Foot  BOV Best Position        Joined Loan Date End    Value  \
0           Left   93            RW   Jul 1, 2004           NaN  €103.5M   
1          Right   92            ST  Jul 10, 2018           NaN     €63M   
2          Right   91            GK  Jul 16, 2014           NaN    €120M   
3          Right   91           CAM  Aug 30, 2015           NaN    €129M   
4          Right   91            LW   Aug 3, 2017           NaN    €132M   
5          Right   91            ST   Jul 1, 2014           NaN    €111M   
6           Left   90            RW   Jul 1, 2017           NaN  €120.5M   
7          Right   90            GK  Jul 19, 2018           NaN    €102M   
8          Right   91            ST   Jul 1, 2018           NaN  €185.5M   
9          Right   90            GK   Jul 1, 2014           NaN    €110M   

    Wage Release Clause  Attacking  Crossing  Finishing  Heading Accuracy  \
0  €560K        €138.4M        429        85         95                70  

In [5]:
# to see the numbers of rows and columns we have in our dataset
data.shape

(18979, 77)

we have 18979 rows and 77 columns in the dataset

lets see the names of the columns we have

In [6]:
# the preview the name of the columns we have in the dataset
data.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 

##### Obeservation
It was observed that some columns do not follow the standard naming convention, some of the column names where separate with space instead of " _ " 

In [7]:
# renaming the columns and replacing white spaces with an underscore
data.columns = [col.replace(" ", "_") for col in data.columns]

lets see if our change is applied

In [8]:
# previewing the column once again to see if there is any further adjustment needed
data.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred_Foot', 'BOV', 'Best_Position', 'Joined', 'Loan_Date_End',
       'Value', 'Wage', 'Release_Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading_Accuracy', 'Short_Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK_Accuracy', 'Long_Passing', 'Ball_Control', 'Movement',
       'Acceleration', 'Sprint_Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot_Power', 'Jumping', 'Stamina', 'Strength', 'Long_Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing_Tackle',
       'Sliding_Tackle', 'Goalkeeping', 'GK_Diving', 'GK_Handling',
       'GK_Kicking', 'GK_Positioning', 'GK_Reflexes', 'Total_Stats',
       'Base_Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 

Lets see some other features of the data

The information method contains the number of columns, column labels, column data types, memory usage, range index, and the number of cells in each column (non-null values).

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                18979 non-null  int64 
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64 
 7   ↓OVA              18979 non-null  int64 
 8   POT               18979 non-null  int64 
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred_Foot    18979 non-null  object
 15  BOV               18979 non-null  int64 
 16  Best_Position     18979 non-null  object
 17  Joined      

Some of the columns are abbreviated the meaning can be found [here](dataset_dictionary.txt). 

Some columns name are not well represented, lets fix that

#### Observation
* The OVA column is not well represented
* The Height and Weight column are of the object type
* Some columns like Loan_Date_End, Hits contains NaN (Null) values

 - ## Cleaning The Data

In [10]:
#the OVA columns is not well spelt
# renaming that particular column is ideal
data.rename(columns = {'↓OVA': 'OVA'}, inplace = True)

In [11]:
# Previewing the columns again to check if the change is applied
data.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       'OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred_Foot', 'BOV', 'Best_Position', 'Joined', 'Loan_Date_End',
       'Value', 'Wage', 'Release_Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading_Accuracy', 'Short_Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK_Accuracy', 'Long_Passing', 'Ball_Control', 'Movement',
       'Acceleration', 'Sprint_Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot_Power', 'Jumping', 'Stamina', 'Strength', 'Long_Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing_Tackle',
       'Sliding_Tackle', 'Goalkeeping', 'GK_Diving', 'GK_Handling',
       'GK_Kicking', 'GK_Positioning', 'GK_Reflexes', 'Total_Stats',
       'Base_Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', '

Now, the column has been successfully renamed

Going back to the data.info() to observe the dataset

We also observed some of the columns contains NAN values or empty values

In [12]:
# Preview the whole dataset for further observation
data.head(5)

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33   93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35   92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27   91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29   91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28   91   

   POT                         Club     Contract   Positions Height Weight  \
0   93         \n\n\n\nFC Barcelona  2004 ~ 2021  RW, ST, CF  170cm   72kg   
1   92             \n\n\n\nJuventus  2018 ~ 2022      ST, LW  187cm   83kg   
2   93      \n\n\n\nAtlético Madrid  2014 ~ 2023          GK  188cm   87kg   
3   91      \n\n\n\nManchester City  2015 ~ 2023     CAM, CM  181cm   70kg   
4   91  \n\n\n\nParis Saint-Germain  2017 ~ 2022     LW, CAM  175cm   68kg   

  Preferred_Foot  BOV Best_Position        Joined Loan_Date_End    Value  \
0           Left   93            RW   Jul 1, 2004           NaN  €103.5M   
1          Right   92            ST  Jul 10, 2018           NaN     €63M   
2          Right   91            GK  Jul 16, 2014           NaN    €120M   
3          Right   91           CAM  Aug 30, 2015           NaN    €129M   
4          Right   91            LW   Aug 3, 2017           NaN    €132M   

    Wage Release_Clause  Attacking  Crossing  Finishing  Heading_Accuracy  \
0  €560K        €138.4M        429        85         95                70   
1  €220K         €75.9M        437        84         95                90   
2  €125K        €159.4M         95        13         11                15   
3  €370K          €161M        407        94         82                55   
4  €270K        €166.5M        408        85         87                62   

   Short_Passing  Volleys  Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   

   Ball_Control  Movement  Acceleration  Sprint_Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   
4            95       453            94            89       96         91   

   Balance  Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   
4       83    357          80       62       81        50          84   

   Mentality  Aggression  Interceptions  Positioning  Vi

#### Another Observation
It was observed that the Club column has some unwanted strings in it

In [13]:
#Lets preview the Club column alone
data.Club.head()

0           \n\n\n\nFC Barcelona
1               \n\n\n\nJuventus
2        \n\n\n\nAtlético Madrid
3        \n\n\n\nManchester City
4    \n\n\n\nParis Saint-Germain
Name: Club, dtype: object

Let remove the unwanted string in the column

In [14]:
# Previewing how the data set will look like if we remove the unwanted char
print(data['Club'].str[4:])

0               FC Barcelona
1                   Juventus
2            Atlético Madrid
3            Manchester City
4        Paris Saint-Germain
                ...         
18974             Wuhan Zall
18975        Oldham Athletic
18976             Derry City
18977       Dalian YiFang FC
18978       Dalian YiFang FC
Name: Club, Length: 18979, dtype: object


In [15]:
# Using the unique mechod to get the unique values present in the dataset
# The Unique value is use to observe if we have abnormalities in that particular column
data['Club'].head().unique()

array(['\n\n\n\nFC Barcelona', '\n\n\n\nJuventus',
       '\n\n\n\nAtlético Madrid', '\n\n\n\nManchester City',
       '\n\n\n\nParis Saint-Germain'], dtype=object)

#### Obersvation
from the Observation, the string char "\n\n\n\n" is common to most of the string characters in that column
we can replace the unwanted string char with an empty string

In [16]:
# replacing the unwanted string character with an empty string
data['Club'] = data['Club'].str.replace('\n\n\n\n', '')

In [17]:
# lets inspect the dataset to see if the change is applied
data.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33   93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35   92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27   91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29   91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28   91   

   POT                 Club     Contract   Positions Height Weight  \
0   93         FC Barcelona  2004 ~ 2021  RW, ST, CF  170cm   72kg   
1   92             Juventus  2018 ~ 2022      ST, LW  187cm   83kg   
2   93      Atlético Madrid  2014 ~ 2023          GK  188cm   87kg   
3   91      Manchester City  2015 ~ 2023     CAM, CM  181cm   70kg   
4   91  Paris Saint-Germain  2017 ~ 2022     LW, CAM  175cm   68kg   

  Preferred_Foot  BOV Best_Position        Joined Loan_Date_End    Value  \
0           Left   93            RW   Jul 1, 2004           NaN  €103.5M   
1          Right   92            ST  Jul 10, 2018           NaN     €63M   
2          Right   91            GK  Jul 16, 2014           NaN    €120M   
3          Right   91           CAM  Aug 30, 2015           NaN    €129M   
4          Right   91            LW   Aug 3, 2017           NaN    €132M   

    Wage Release_Clause  Attacking  Crossing  Finishing  Heading_Accuracy  \
0  €560K        €138.4M        429        85         95                70   
1  €220K         €75.9M        437        84         95                90   
2  €125K        €159.4M         95        13         11                15   
3  €370K          €161M        407        94         82                55   
4  €270K        €166.5M        408        85         87                62   

   Short_Passing  Volleys  Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   

   Ball_Control  Movement  Acceleration  Sprint_Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   
4            95       453            94            89       96         91   

   Balance  Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   
4       83    357          80       62       81        50          84   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
0        347          44     

#### Further cleaning
Also, for our Height and Weight, We can rename the columns to carry the SI unit, then removing the unit from the entire column, and then convert the column to an int type

In [18]:
# renaming the Height column to by adding the SI of the height to it

data.rename(columns = {'Height': 'Height_cm'}, inplace = True)

In [19]:
# renaming the Weight column to by adding the SI of weight to it

data.rename(columns = {'Weight': 'Weight_kg'}, inplace = True)

In [20]:
# Inspecting the dataset to see if the change is applied
data.head(4)

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   

                                           playerUrl Nationality  Age  OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33   93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35   92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27   91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29   91   

   POT             Club     Contract   Positions Height_cm Weight_kg  \
0   93     FC Barcelona  2004 ~ 2021  RW, ST, CF     170cm      72kg   
1   92         Juventus  2018 ~ 2022      ST, LW     187cm      83kg   
2   93  Atlético Madrid  2014 ~ 2023          GK     188cm      87kg   
3   91  Manchester City  2015 ~ 2023     CAM, CM     181cm      70kg   

  Preferred_Foot  BOV Best_Position        Joined Loan_Date_End    Value  \
0           Left   93            RW   Jul 1, 2004           NaN  €103.5M   
1          Right   92            ST  Jul 10, 2018           NaN     €63M   
2          Right   91            GK  Jul 16, 2014           NaN    €120M   
3          Right   91           CAM  Aug 30, 2015           NaN    €129M   

    Wage Release_Clause  Attacking  Crossing  Finishing  Heading_Accuracy  \
0  €560K        €138.4M        429        85         95                70   
1  €220K         €75.9M        437        84         95                90   
2  €125K        €159.4M         95        13         11                15   
3  €370K          €161M        407        94         82                55   

   Short_Passing  Volleys  Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   

   Ball_Control  Movement  Acceleration  Sprint_Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   

   Balance  Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
0        347          44             40           93      95         75   
1        353          63             29           95      82         84   
2        140          34             19           11      65         11   
3        408          76             66           88      94         84   

   Composure  Defending  Marking  Standing_Tackle  Sliding_Tackle  \
0         96         91       32               35              24   
1         95         84       28               32              24   
2         68         57       27               12              18   
3         91        186       68               65              53   

   Goalkeeping  GK_Di

Since the Height column has been renamed, we can now remove the SI from the entire column.
before then, lets see if there are some abnormal values in the column

### Cleaning the Height column

In [21]:
# using the unique() method to see the unique values contained in the data set
data['Height_cm'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

From our observation, not all the values in the height column are represented in centimeters(cm),
We will remove the cm from all the values in the column 
also, we will clean the abnormal values which was represented in ft-inches and then convert it to cm

In [22]:
# replace the values that are represented in ft, inches and converting it to centimetres

In [23]:
#to define a function that will do the conversion, i will be using the unique last value as a reference
data['Height_cm'].str[-1].unique()

array(['m', '"'], dtype=object)

In [24]:
# define a function 
#using the unique last value as a reference of condition
# replacing the unwant string value with an empty string
# converting the concerned value from their respective units to centimeter
# Adding both units to complete the conversion
# return the answer
# if else, resume the other centimeter value without the cm
def convert_height(x):
    if x[-1] == '"':
        x = x.replace("\"","")
        inch = int(x[2:]) * 2.54
        foot = int(x[0]) * 30.48
        return round(foot+inch)
    elif x[-1] == "m":
        return int(x[:-2])


In [25]:
# Applying the function to the Height column
data['Height_cm'] = data['Height_cm'].apply(convert_height)

In [26]:
#checking if the change is applied
data['Height_cm'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155])

In [27]:
data['Height_cm'].isnull().sum()

0

### Cleaning the weight column
Also for the Weight column, we will convert the lbs to kg

Also for the weight column

In [28]:
#previewing the unique values of the weight column the SI units are both kg and lbs
data['Weight_kg'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [29]:
#to define a function that will do the conversion, i will be using the unique last value as a reference
data['Weight_kg'].str[-1].unique()

array(['g', 's'], dtype=object)

In [30]:
# define a function 
#using the unique last value as a reference of condition
# replacing the unwant string value with an empty string
# converting the concerned value from it unit to Kilogram
# return the rounded off answer
# if else, preserve the other kilogram value without the kg

def convert_weight(x):
    if x[-1] == 's':
        x = x.replace("lbs","")
        kg = int(x[:3]) / 2.205
        return round(kg)
    elif x[-1] == "g":
        return int(x[:-2])

In [31]:
# Applying the function to the weight column 
data['Weight_kg'] = data['Weight_kg'].apply(convert_weight)

In [32]:
# checking to see if the change is applied
data['Weight_kg'].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52])

In [33]:
#Previewing the data set
data.head(5)

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33   93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35   92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27   91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29   91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28   91   

   POT                 Club     Contract   Positions  Height_cm  Weight_kg  \
0   93         FC Barcelona  2004 ~ 2021  RW, ST, CF        170         72   
1   92             Juventus  2018 ~ 2022      ST, LW        187         83   
2   93      Atlético Madrid  2014 ~ 2023          GK        188         87   
3   91      Manchester City  2015 ~ 2023     CAM, CM        181         70   
4   91  Paris Saint-Germain  2017 ~ 2022     LW, CAM        175         68   

  Preferred_Foot  BOV Best_Position        Joined Loan_Date_End    Value  \
0           Left   93            RW   Jul 1, 2004           NaN  €103.5M   
1          Right   92            ST  Jul 10, 2018           NaN     €63M   
2          Right   91            GK  Jul 16, 2014           NaN    €120M   
3          Right   91           CAM  Aug 30, 2015           NaN    €129M   
4          Right   91            LW   Aug 3, 2017           NaN    €132M   

    Wage Release_Clause  Attacking  Crossing  Finishing  Heading_Accuracy  \
0  €560K        €138.4M        429        85         95                70   
1  €220K         €75.9M        437        84         95                90   
2  €125K        €159.4M         95        13         11                15   
3  €370K          €161M        407        94         82                55   
4  €270K        €166.5M        408        85         87                62   

   Short_Passing  Volleys  Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   
4             87       87    448         95     88           89            81   

   Ball_Control  Movement  Acceleration  Sprint_Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   
4            95       453            94            89       96         91   

   Balance  Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   
4       83    357          80       62       81        50          84   

   Mentality  Aggression  Interceptions  Positioning  Vi

## Moving on with cleaning other columns

Also according to the info() of the dataset, some other columns needs cleaning

### Cleaning The Contract Column

In [34]:
# Checking the unique values in the contract column
data['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 

Its is observed that some players have year range contracts which includes the date and year of expiration,
Some players are on loan with year of expiration
Some players are on Free contracts

So Idealy,it is ideal to convert the column into a categorical column, i will be using the last value on each column as a reference for my python function

In [35]:
#Some row with the year range contains the range of 0 - 9 as their last string value
str(list(range(10)))

'[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'

In [36]:
# see the unique last value of the contract column
data['Contract'].str[-1].unique()

array(['1', '2', '3', '4', '5', '6', 'n', 'e', '8', '0', '7'],
      dtype=object)

In [37]:
#Using a function to set values for each rows containing the unique last values used as reference

def convert_Cont(x):
    if x[-1] in str(list(range(10))):
        x = 'Active'
        return x
    elif x[-1] == 'n':
        x = 'Loan'
        return x
    elif x[-1] == 'e':
        x = 'Free'
        return x
        

In [38]:
#Applying the function
data['Contract'] = data['Contract'].apply(convert_Cont)

In [39]:
#converting the column into a categorical type 
data['Contract'] = data['Contract'].astype('category')

In [40]:
#renaming the column from contract to contract status
data.rename(columns = {'Contract': 'Contract_Status'}, inplace = True)

In [41]:
data[data['Contract_Status'] == 'Free']

ID            Name                          LongName  \
289    230347  Welington Dano    Welington Kauê Dano Nascimento   
292    230225  Juiano Mestres  Juan Everton Mestres de Mesquita   
369    245299     J. Frendado            Jaime Nicolás Frendado   
374    245294    J. Serendero          Jorge Ezequiel Serendero   
375    245308        M. Nérez                Mauro Evidio Nérez   
...       ...             ...                               ...   
17220  247059   A. Al Hidhani                    Ali Al Hidhani   
17343  251734       A. Sanghu                    Anudaan Sanghu   
17659  251738        M. Chada                   Madanapal Chada   
17661  251741       E. Suresh                Eelamynthan Suresh   
18205  251737       J. Mangat                  Jagatjiva Mangat   

                                               photoUrl  \
289    https://cdn.sofifa.com/players/230/347/21_60.png   
292    https://cdn.sofifa.com/players/230/225/21_60.png   
369    https://cdn.sofifa.com/players/245/299/21_60.png   
374    https://cdn.sofifa.com/players/245/294/21_60.png   
375    https://cdn.sofifa.com/players/245/308/21_60.png   
...                                                 ...   
17220  https://cdn.sofifa.com/players/247/059/21_60.png   
17343  https://cdn.sofifa.com/players/251/734/21_60.png   
17659  https://cdn.sofifa.com/players/251/738/21_60.png   
17661  https://cdn.sofifa.com/players/251/741/21_60.png   
18205  https://cdn.sofifa.com/players/251/737/21_60.png   

                                               playerUrl  \
289    http://sofifa.com/player/230347/welington-kaue...   
292    http://sofifa.com/player/230225/juan-everton-m...   
369    http://sofifa.com/player/245299/jaime-nicolas-...   
374    http://sofifa.com/player/245294/jorge-ezequiel...   
375    http://sofifa.com/player/245308/mauro-evidio-n...   
...                                                  ...   
17220  http://sofifa.com/player/247059/ali-al-hidhani...   
17343  http://sofifa.com/player/251734/anudaan-sanghu...   
17659  http://sofifa.com/player/251738/madanapal-chad...   
17661  http://sofifa.com/player/251741/eelamynthan-su...   
18205  http://sofifa.com/player/251737/jagatjiva-mang...   

                Nationality  Age  OVA  POT     Club Contract_Status  \
289                  Brazil   20   81   81  No Club            Free   
292                  Brazil   24   81   81  No Club            Free   
369                 Uruguay   36   80   80  No Club            Free   
374                 Uruguay   32   80   80  No Club            Free   
375                 Uruguay   32   80   80  No Club            Free   
...                     ...  ...  ...  ...      ...             ...   
17220  United Arab Emirates   22   56   64  No Club            Free   
17343                 India   20   56   56  No Club            Free   
17659                 India   27   55   55  No Club            Free   
17661                 India   28   55   55  No Club            Free   
18205                 India   26   53   54  No Club            Free   

         Positions  Height_cm  Weight_kg Preferred_Foot  BOV Best_Position  \
289         LB, LM        178         69           Left   81            LB   
292        CB, CDM        181         82          Right   81            CB   
369        CB, CDM        181         82          Right   80            CB   
374             GK        190         85          Right   80            GK   
375         LB, LM        178         69           Left   80            LB   
...            ...        ...        ...            ...  ...           ...   
17220           RB        172         67          Right   56            RB   
17343       RM, CM        168         62          Right   56            RM   
17659           ST        178         77          Right   57            RM   
17661  RM, CAM, RB        175         73           Left   55            RM   
18205           LM        171         65           Left   53     

### Cleaning The Loan_Date_End Column

Before cleaning the column, lets analyse it carefully

In [42]:
#Getting the uniqu values in the column
data['Loan_Date_End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

It is observed that the column contains NAN (Missing values) values

Let see how many NAN values is in the column

In [43]:
#Getting the number of Nan value in the Load_Date_End column
data['Loan_Date_End'].isnull().sum()

17966

There are 17966 missing value in the Load_date_End, since the amount of missing is far greater than the Available values, It is ideal to drop the entire column, Not all players are on loan, The Contract_Status column already justified that

In [44]:
# Removing the Loan_Date_End from the data
data = data.drop('Loan_Date_End', axis=1)

In [45]:
#Checking if our change is applied
data.head(4)

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   

                                           playerUrl Nationality  Age  OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33   93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35   92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27   91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29   91   

   POT             Club Contract_Status   Positions  Height_cm  Weight_kg  \
0   93     FC Barcelona          Active  RW, ST, CF        170         72   
1   92         Juventus          Active      ST, LW        187         83   
2   93  Atlético Madrid          Active          GK        188         87   
3   91  Manchester City          Active     CAM, CM        181         70   

  Preferred_Foot  BOV Best_Position        Joined    Value   Wage  \
0           Left   93            RW   Jul 1, 2004  €103.5M  €560K   
1          Right   92            ST  Jul 10, 2018     €63M  €220K   
2          Right   91            GK  Jul 16, 2014    €120M  €125K   
3          Right   91           CAM  Aug 30, 2015    €129M  €370K   

  Release_Clause  Attacking  Crossing  Finishing  Heading_Accuracy  \
0        €138.4M        429        85         95                70   
1         €75.9M        437        84         95                90   
2        €159.4M         95        13         11                15   
3          €161M        407        94         82                55   

   Short_Passing  Volleys  Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  \
0             91       88    470         96     93           94            91   
1             82       86    414         88     81           76            77   
2             43       13    109         12     13           14            40   
3             94       82    441         88     85           83            93   

   Ball_Control  Movement  Acceleration  Sprint_Speed  Agility  Reactions  \
0            96       451            91            80       91         94   
1            92       431            87            91       87         95   
2            30       307            43            60       67         88   
3            92       398            77            76       78         91   

   Balance  Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
0       95    389          86       68       72        69          94   
1       71    444          94       95       84        78          93   
2       49    268          59       78       41        78          12   
3       76    408          91       63       89        74          91   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
0        347          44             40           93      95         75   
1        353          63             29           95      82         84   
2        140          34             19           11      65         11   
3        408          76             66           88      94         84   

   Composure  Defending  Marking  Standing_Tackle  Sliding_Tackle  \
0         96         91       32               35              24   
1         95         84       28               32              24   
2         68         57       27               12              18   
3         91        186       68               65              53   

   Goalkeeping  GK_Diving  GK_Handling  GK_Kicking  GK_Positioning

### Cleaning Prefer foot column

In [46]:
#Checking for Uniqueness
data['Preferred_Foot'].unique()

array(['Left', 'Right'], dtype=object)

Since This column contains two type of Uniqueness, we can convert it to a categorical column

In [47]:
data['Preferred_Foot'] = data['Preferred_Foot'].astype('category')

### Cleaning The Joined Column

In [48]:
# Checking for the Uniqueness
data['Joined'].unique()

array(['Jul 1, 2004', 'Jul 10, 2018', 'Jul 16, 2014', ..., 'Sep 22, 2018',
       'Feb 28, 2015', 'Mar 6, 2018'], dtype=object)

This column contains the date the player Joined Fifa. So, it can be converted to a datetime column

In [49]:
#Using the pandas library to convert the Joined Column into a datatime

data['Joined'] = pd.to_datetime(data['Joined'])
print(data['Joined'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 18979 entries, 0 to 18978
Series name: Joined
Non-Null Count  Dtype         
--------------  -----         
18979 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 148.4 KB
None


In [50]:
#Checking if the change is applied
data.head(3)

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   

                                           playerUrl Nationality  Age  OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33   93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35   92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27   91   

   POT             Club Contract_Status   Positions  Height_cm  Weight_kg  \
0   93     FC Barcelona          Active  RW, ST, CF        170         72   
1   92         Juventus          Active      ST, LW        187         83   
2   93  Atlético Madrid          Active          GK        188         87   

  Preferred_Foot  BOV Best_Position     Joined    Value   Wage Release_Clause  \
0           Left   93            RW 2004-07-01  €103.5M  €560K        €138.4M   
1          Right   92            ST 2018-07-10     €63M  €220K         €75.9M   
2          Right   91            GK 2014-07-16    €120M  €125K        €159.4M   

   Attacking  Crossing  Finishing  Heading_Accuracy  Short_Passing  Volleys  \
0        429        85         95                70             91       88   
1        437        84         95                90             82       86   
2         95        13         11                15             43       13   

   Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  Movement  \
0    470         96     93           94            91            96       451   
1    414         88     81           76            77            92       431   
2    109         12     13           14            40            30       307   

   Acceleration  Sprint_Speed  Agility  Reactions  Balance  Power  Shot_Power  \
0            91            80       91         94       95    389          86   
1            87            91       87         95       71    444          94   
2            43            60       67         88       49    268          59   

   Jumping  Stamina  Strength  Long_Shots  Mentality  Aggression  \
0       68       72        69          94        347          44   
1       95       84        78          93        353          63   
2       78       41        78          12        140          34   

   Interceptions  Positioning  Vision  Penalties  Composure  Defending  \
0             40           93      95         75         96         91   
1             29           95      82         84         95         84   
2             19           11      65         11         68         57   

   Marking  Standing_Tackle  Sliding_Tackle  Goalkeeping  GK_Diving  \
0       32               35              24           54          6   
1       28               32              24           58          7   
2       27               12              18          437         87   

   GK_Handling  GK_Kicking  GK_Positioning  GK_Reflexes  Total_Stats  \
0           11          15              14            8         2231   
1           11          15              14           11         2221   
2           92          78              90           90         1413   

   Base_Stats  W/F  SM     A/W     D/W   IR  PAC  SHO  PAS  DRI  DEF  PHY Hits  
0         466  4 ★  4★  Medium     Low  5 ★   85   92   91   95   38   65  771  
1         464  4 ★  5★    High     Low  5 ★   89   93   81   89   35   77  562  
2         489  3 ★  1★  Medium  Medium  3 ★   87   92   78   90   52   90  150

### Cleaning the Best Position Column

Let is first analyse the type of values in the Best Position column

In [51]:
# We preview the unique values in that column
data['Best_Position'].unique()

array(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',
       'LM', 'RM', 'LWB', 'RWB'], dtype=object)

We can observe that it contain the best position fit for the player, and it looks like it is categorical. We can then convert the column into a categorical column

In [52]:
#converting the Best_Position column into a categorical type
data['Best_Position'] = data['Best_Position'].astype('category')

# Checking if the change is applied
print(data['Best_Position'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 18979 entries, 0 to 18978
Series name: Best_Position
Non-Null Count  Dtype   
--------------  -----   
18979 non-null  category
dtypes: category(1)
memory usage: 19.3 KB
None


### Setting the Joined Column in ascending order

Rearranging the Joined column in ascending order and setting it as the Index of the dataframe

This enable us to when the players joined in ascending order

In [53]:
#Arrange the Joined column inscending order
data.sort_values(by='Joined', inplace=True)

#Setting the Joined column as Index
data.set_index('Joined', inplace=True) 

In [54]:
 
#Setting the Joined column as Index
data.head()

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   
2002-08-01  138830   D. Lewington    Dean Lewington   
2003-01-01  142333     M. McNulty      Mark McNulty   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   
2002-08-01  https://cdn.sofifa.com/players/138/830/21_60.png   
2003-01-01  https://cdn.sofifa.com/players/142/333/21_60.png   

                                                    playerUrl  \
Joined                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...   
2002-08-01  http://sofifa.com/player/138830/dean-lewington...   
2003-01-01  http://sofifa.com/player/142333/mark-mcnulty/2...   

                    Nationality  Age  OVA  POT                Club  \
Joined                                                               
1998-01-01                Japan   40   65   65     Kashima Antlers   
2002-01-01       Korea Republic   37   70   70     Pohang Steelers   
2002-01-01               Russia   34   80   80     PFC CSKA Moscow   
2002-08-01              England   36   65   65  Milton Keynes Dons   
2003-01-01  Republic of Ireland   39   60   60           Cork City   

           Contract_Status Positions  Height_cm  Weight_kg Preferred_Foot  \
Joined                                                                      
1998-01-01          Active        GK        187         80          Right   
2002-01-01          Active        CB        183         73          Right   
2002-01-01          Active        GK        186         78          Right   
2002-08-01          Active   LB, LWB        183         86           Left   
2003-01-01          Active        GK        190         70          Right   

            BOV Best_Position  Value  Wage Release_Clause  Attacking  \
Joined                                                                 
1998-01-01   65            GK   €80K   €1K           €63K         87   
2002-01-01   70            CB  €275K   €3K          €438K        260   
2002-01-01   80            GK  €3.6M  €40K         €10.4M         83   
2002-08-01   65            LB  €160K   €2K          €175K        229   
2003-01-01   60            GK   €25K  €500           €31K         90   

            Crossing  Finishing  Heading_Accuracy  Short_Passing  Volleys  \
Joined                                                                      
1998-01-01        13         12                18             26       18   
2002-01-01        58         38                70             55       39   
2002-01-01        19         13                18             23       10   
2002-08-01        66         22                58             65       18   
2003-01-01        16         12                12             36       14   

            Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  \
Joined                                                                         
1998-01-01     84         14     10           11            33            16   
2002-01-01    232         51     46           30            49            56   
2002-01-01     91         15     19           13            22            22   
2002-08-01    300         54     59           64            62            61   
2003-01-01     89         12     19           12            23            23   

            Movement  Acceleration  Sprint_Speed  Agility  Reactions  Balance  \
Joined 

### Cleaning the Value Column

In [55]:
#Let see how the values in the Value columnn looks like

data['Value'].unique()

array(['€80K', '€275K', '€3.6M', '€160K', '€25K', '€400K', '€600K',
       '€35K', '€180K', '€70K', '€550K', '€575K', '€230K', '€1M',
       '€103.5M', '€3.5M', '€1.2M', '€850K', '€0', '€240K', '€1.5M',
       '€110K', '€21M', '€1.6M', '€33.5M', '€500K', '€825K', '€375K',
       '€3.7M', '€475K', '€25M', '€925K', '€90K', '€800K', '€130K',
       '€15.5M', '€1.3M', '€625K', '€325K', '€2.4M', '€1.4M', '€4.9M',
       '€7M', '€700K', '€6.5M', '€425K', '€2.9M', '€750K', '€2.6M',
       '€190K', '€18.5M', '€875K', '€60K', '€32.5M', '€65.5M', '€56M',
       '€1.1M', '€2.1M', '€12.5M', '€210K', '€675K', '€10M', '€150K',
       '€7.5M', '€4.6M', '€450K', '€8.5M', '€83.5M', '€4.1M', '€38.5M',
       '€22M', '€975K', '€120K', '€950K', '€2.5M', '€775K', '€900K',
       '€36.5M', '€2.7M', '€5.5M', '€14.5M', '€2M', '€2.3M', '€32M',
       '€220K', '€12M', '€4.8M', '€109M', '€53M', '€14M', '€4M', '€22.5M',
       '€3.8M', '€17.5M', '€6M', '€1.9M', '€350K', '€54M', '€20K',
       '€1.8M', '€300K', '€

we observe that the value have Euro sign as the prefix and M,K as the suffix

We are going to remove the Euro sign from the entire value in the column and the M as Millions and K as thousand, then wr can convert the column to an int type

Also we are going to rename the column so that it can indicate the type of currency used to estimate the player's value

In [56]:
# Defining a function that can elimated the unwanted string and will convert the values into integers
def clean_value(x):
    # replacing the euro sign with an empty string
    x = x.replace('€', '')
    # setting a condition if there is K in the column it should remove it 
    # and then convert the value to a float
    # then multipy the value by 1000
    if  'K' in x:
        x = x.replace('K', '')
        x = float(x)*1000
        # return the answer as a rounded off value
        return round(x)
    # setting a condition if there is M in the column it should remove it 
    # and then convert the value to a float
    # then multipy the value by 1000000
    elif 'M' in x:
        x = x.replace('M','')
        x = float(x)*1000000
        # return the answer as a rounded off value
        return round(x)
    # setting a condition if there is B in the column it should remove it 
    # and then convert the value to a float
    # then multipy the value by 1000000000
    elif 'B' in x:
        x = x.replace('B','')
        x = float(x)*1000000000
        # return the answer as a rounded off value
        return round(x)
    # setting a condition if there is 0 in the column
    # it should convert it to a float
    elif '0' in x:
        x = float(x)
    # returning it as a rounded off value
        return round(x)

In [57]:
# Applying the function to the Value Column
data['Value'] = data['Value'].apply(clean_value)

In [58]:
# checking if the changes are applied
data['Value'].unique()

array([    80000,    275000,   3600000,    160000,     25000,    400000,
          600000,     35000,    180000,     70000,    550000,    575000,
          230000,   1000000, 103500000,   3500000,   1200000,    850000,
               0,    240000,   1500000,    110000,  21000000,   1600000,
        33500000,    500000,    825000,    375000,   3700000,    475000,
        25000000,    925000,     90000,    800000,    130000,  15500000,
         1300000,    625000,    325000,   2400000,   1400000,   4900000,
         7000000,    700000,   6500000,    425000,   2900000,    750000,
         2600000,    190000,  18500000,    875000,     60000,  32500000,
        65500000,  56000000,   1100000,   2100000,  12500000,    210000,
          675000,  10000000,    150000,   7500000,   4600000,    450000,
         8500000,  83500000,   4100000,  38500000,  22000000,    975000,
          120000,    950000,   2500000,    775000,    900000,  36500000,
         2700000,   5500000,  14500000,   2000000, 

 - ##### We can now rename the Value column so it can represent the currency used

In [59]:
# renaming the column from Value to Value_Euro
data.rename(columns = {'Value': 'Value_in_Euro'}, inplace = True)

### Cleaning Wage Column 

We are going to remove the Euro sign from the entire value in the column and the M as Millions and K as thousand, then wr can convert the column to an int type

Also we are going to rename the column so that it can indicate the type of currency used to estimate the player's value

In [60]:
# Checking the unique values in the wage column 
data['Wage'].unique()

array(['€1K', '€3K', '€40K', '€2K', '€500', '€4K', '€6K', '€5K', '€650',
       '€560K', '€36K', '€7K', '€0', '€8K', '€700', '€95K', '€12K',
       '€19K', '€300K', '€30K', '€170K', '€800', '€9K', '€85K', '€37K',
       '€10K', '€51K', '€850', '€15K', '€38K', '€17K', '€16K', '€220K',
       '€130K', '€240K', '€29K', '€11K', '€24K', '€76K', '€23K', '€25K',
       '€49K', '€350K', '€950', '€41K', '€72K', '€105K', '€60K', '€900',
       '€71K', '€34K', '€28K', '€120K', '€56K', '€21K', '€44K', '€33K',
       '€135K', '€550', '€14K', '€90K', '€600', '€13K', '€42K', '€32K',
       '€59K', '€26K', '€140K', '€150K', '€31K', '€27K', '€750', '€79K',
       '€18K', '€35K', '€69K', '€20K', '€82K', '€64K', '€46K', '€22K',
       '€48K', '€65K', '€160K', '€53K', '€50K', '€39K', '€100K', '€260K',
       '€58K', '€84K', '€125K', '€70K', '€55K', '€115K', '€78K', '€110K',
       '€175K', '€86K', '€210K', '€54K', '€67K', '€230K', '€310K', '€43K',
       '€200K', '€57K', '€73K', '€63K', '€66K', '€68K', '€

We will be removing the Euro sign and changing K to thousanf and converting the column to an integer

We can also use the same function used for the Value column too

In [61]:
# we will apply the clean Value function on the wage column

data['Wage'] = data['Wage'].apply(clean_value)

In [62]:
# Checking if our changes applies
data['Wage'].unique()

array([  1000,   3000,  40000,   2000,    500,   4000,   6000,   5000,
          650, 560000,  36000,   7000,      0,   8000,    700,  95000,
        12000,  19000, 300000,  30000, 170000,    800,   9000,  85000,
        37000,  10000,  51000,    850,  15000,  38000,  17000,  16000,
       220000, 130000, 240000,  29000,  11000,  24000,  76000,  23000,
        25000,  49000, 350000,    950,  41000,  72000, 105000,  60000,
          900,  71000,  34000,  28000, 120000,  56000,  21000,  44000,
        33000, 135000,    550,  14000,  90000,    600,  13000,  42000,
        32000,  59000,  26000, 140000, 150000,  31000,  27000,    750,
        79000,  18000,  35000,  69000,  20000,  82000,  64000,  46000,
        22000,  48000,  65000, 160000,  53000,  50000,  39000, 100000,
       260000,  58000,  84000, 125000,  70000,  55000, 115000,  78000,
       110000, 175000,  86000, 210000,  54000,  67000, 230000, 310000,
        43000, 200000,  57000,  73000,  63000,  66000,  68000,  47000,
      

In [63]:
# renaming the column from Value to Value_Euro
data.rename(columns = {'Wage': 'Wage_in_Euro'}, inplace = True)

In [64]:
# confirming the type of column the Wage is 
print(data['Wage_in_Euro'].info())

<class 'pandas.core.series.Series'>
DatetimeIndex: 18979 entries, 1998-01-01 to 2020-10-08
Series name: Wage_in_Euro
Non-Null Count  Dtype
--------------  -----
18979 non-null  int64
dtypes: int64(1)
memory usage: 296.5 KB
None


In [65]:
data.head(3)

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   

                                                    playerUrl     Nationality  \
Joined                                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...           Japan   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...  Korea Republic   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...          Russia   

            Age  OVA  POT             Club Contract_Status Positions  \
Joined                                                                 
1998-01-01   40   65   65  Kashima Antlers          Active        GK   
2002-01-01   37   70   70  Pohang Steelers          Active        CB   
2002-01-01   34   80   80  PFC CSKA Moscow          Active        GK   

            Height_cm  Weight_kg Preferred_Foot  BOV Best_Position  \
Joined                                                               
1998-01-01        187         80          Right   65            GK   
2002-01-01        183         73          Right   70            CB   
2002-01-01        186         78          Right   80            GK   

            Value_in_Euro  Wage_in_Euro Release_Clause  Attacking  Crossing  \
Joined                                                                        
1998-01-01          80000          1000           €63K         87        13   
2002-01-01         275000          3000          €438K        260        58   
2002-01-01        3600000         40000         €10.4M         83        19   

            Finishing  Heading_Accuracy  Short_Passing  Volleys  Skill  \
Joined                                                                   
1998-01-01         12                18             26       18     84   
2002-01-01         38                70             55       39    232   
2002-01-01         13                18             23       10     91   

            Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  \
Joined                                                                  
1998-01-01         14     10           11            33            16   
2002-01-01         51     46           30            49            56   
2002-01-01         15     19           13            22            22   

            Movement  Acceleration  Sprint_Speed  Agility  Reactions  Balance  \
Joined                                                                          
1998-01-01       143            17            19       28         47       32   
2002-01-01       325            69            61       54         73       68   
2002-01-01       270            51            50       53         71       45   

            Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
Joined                                                                  
1998-01-01    203          48       52       37        51          15   
2002-01-01    316          48       89       63        75          41   
2002-01-01    241          59       62       35        72          13   

            Mentality  Aggression  Interceptions  Positioning  Vision  \
Joined                                                                  
1998-01-01        100          21             12           10      45   
2002-01-01        285          71             73           55      43   
2002-01-01        121          24             17           11      59   

            Penalties  Composu

### Cleaning Release_Clause Column

We are going to remove the Euro sign from the entire value in the column and the M as Millions and K as thousand, then wr can convert the column to an int type

Also we are going to rename the column so that it can indicate the type of currency used to estimate the player's value

In [66]:
# Checking the unique values in the wage column 
data['Release_Clause'].unique()

array(['€63K', '€438K', '€10.4M', ..., '€69.1M', '€61.2M', '€47.7M'],
      dtype=object)

We will be removing the Euro sign and changing K to thousang and converting the column to an integer

We can also use the same function used for the Value column too

In [67]:
# we will apply the clean Value function on the Release_Clause column

data['Release_Clause'] = data['Release_Clause'].apply(clean_value)

In [68]:
data['Release_Clause'].unique()

array([   63000,   438000, 10400000, ..., 69100000, 61200000, 47700000])

In [69]:
# renaming the column from Release_Clause to Release_Clause_in_Euro
data.rename(columns = {'Release_Clause': 'Release_Clause_in_Euro'}, inplace = True)

In [70]:
data.head()

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   
2002-08-01  138830   D. Lewington    Dean Lewington   
2003-01-01  142333     M. McNulty      Mark McNulty   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   
2002-08-01  https://cdn.sofifa.com/players/138/830/21_60.png   
2003-01-01  https://cdn.sofifa.com/players/142/333/21_60.png   

                                                    playerUrl  \
Joined                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...   
2002-08-01  http://sofifa.com/player/138830/dean-lewington...   
2003-01-01  http://sofifa.com/player/142333/mark-mcnulty/2...   

                    Nationality  Age  OVA  POT                Club  \
Joined                                                               
1998-01-01                Japan   40   65   65     Kashima Antlers   
2002-01-01       Korea Republic   37   70   70     Pohang Steelers   
2002-01-01               Russia   34   80   80     PFC CSKA Moscow   
2002-08-01              England   36   65   65  Milton Keynes Dons   
2003-01-01  Republic of Ireland   39   60   60           Cork City   

           Contract_Status Positions  Height_cm  Weight_kg Preferred_Foot  \
Joined                                                                      
1998-01-01          Active        GK        187         80          Right   
2002-01-01          Active        CB        183         73          Right   
2002-01-01          Active        GK        186         78          Right   
2002-08-01          Active   LB, LWB        183         86           Left   
2003-01-01          Active        GK        190         70          Right   

            BOV Best_Position  Value_in_Euro  Wage_in_Euro  \
Joined                                                       
1998-01-01   65            GK          80000          1000   
2002-01-01   70            CB         275000          3000   
2002-01-01   80            GK        3600000         40000   
2002-08-01   65            LB         160000          2000   
2003-01-01   60            GK          25000           500   

            Release_Clause_in_Euro  Attacking  Crossing  Finishing  \
Joined                                                               
1998-01-01                   63000         87        13         12   
2002-01-01                  438000        260        58         38   
2002-01-01                10400000         83        19         13   
2002-08-01                  175000        229        66         22   
2003-01-01                   31000         90        16         12   

            Heading_Accuracy  Short_Passing  Volleys  Skill  Dribbling  Curve  \
Joined                                                                          
1998-01-01                18             26       18     84         14     10   
2002-01-01                70             55       39    232         51     46   
2002-01-01                18             23       10     91         15     19   
2002-08-01                58             65       18    300         54     59   
2003-01-01                12             36       14     89         12     19   

            FK_Accuracy  Long_Passing  Ball_Control  Movement  Acceleration  \
Joined                                                                        
1998-01-01           11            33     

### Cleaning The W/F column

In [71]:
# Previewing the unique values in the W/F column
data['W/F'].unique()

array(['3 ★', '2 ★', '4 ★', '1 ★', '5 ★'], dtype=object)

From observation, the W/F column represent a rating, it represent the situation of the player's weaker foot

It can be considered as categorigal also

But we have to remove the unwanted character from it
we will be removing the star from it '★'

In [72]:
# I prefer to use a function to achieve this since there might be other column that might have similar situation
# also using the function to convert it to an interger

def remove_star(x):
    # replace the star with empty string
    x = x.replace('★', '')
    # return the integer version the column
    return int(x)

In [73]:
# Apply the function to W/F column 
data['W/F'] = data['W/F'].apply(remove_star)


We may want to as well rename the column from W/F_rating for better understanding

In [74]:
data.rename(columns = {'W/F': 'WF_Rate'}, inplace = True)

In [75]:
# Checking if the change is applied
data.head(3)

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   

                                                    playerUrl     Nationality  \
Joined                                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...           Japan   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...  Korea Republic   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...          Russia   

            Age  OVA  POT             Club Contract_Status Positions  \
Joined                                                                 
1998-01-01   40   65   65  Kashima Antlers          Active        GK   
2002-01-01   37   70   70  Pohang Steelers          Active        CB   
2002-01-01   34   80   80  PFC CSKA Moscow          Active        GK   

            Height_cm  Weight_kg Preferred_Foot  BOV Best_Position  \
Joined                                                               
1998-01-01        187         80          Right   65            GK   
2002-01-01        183         73          Right   70            CB   
2002-01-01        186         78          Right   80            GK   

            Value_in_Euro  Wage_in_Euro  Release_Clause_in_Euro  Attacking  \
Joined                                                                       
1998-01-01          80000          1000                   63000         87   
2002-01-01         275000          3000                  438000        260   
2002-01-01        3600000         40000                10400000         83   

            Crossing  Finishing  Heading_Accuracy  Short_Passing  Volleys  \
Joined                                                                      
1998-01-01        13         12                18             26       18   
2002-01-01        58         38                70             55       39   
2002-01-01        19         13                18             23       10   

            Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  \
Joined                                                                         
1998-01-01     84         14     10           11            33            16   
2002-01-01    232         51     46           30            49            56   
2002-01-01     91         15     19           13            22            22   

            Movement  Acceleration  Sprint_Speed  Agility  Reactions  Balance  \
Joined                                                                          
1998-01-01       143            17            19       28         47       32   
2002-01-01       325            69            61       54         73       68   
2002-01-01       270            51            50       53         71       45   

            Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
Joined                                                                  
1998-01-01    203          48       52       37        51          15   
2002-01-01    316          48       89       63        75          41   
2002-01-01    241          59       62       35        72          13   

            Mentality  Aggression  Interceptions  Positioning  Vision  \
Joined                                                                  
1998-01-01        100          21             12           10      45   
2002-01-01        285          71             73           55      43   
2002-01-01        121          24             17           

### Cleaning The SM column

In [76]:
# Previewing the unique values in the SM column
data['SM'].unique()

array(['1★', '2★', '3★', '4★', '5★'], dtype=object)

From observation, the SM column represent a rating, it represent the situation of the player's skill moves ability

It can be considered as categorigal also

But we have to remove the unwanted character from it
we will be removing the star from it '★'



In [77]:
# Apply the function to W/F column 
data['SM'] = data['SM'].apply(remove_star)

We may want to as well rename the column to SM_rate for better understanding

In [78]:
data.rename(columns = {'SM': 'SM_Rate'}, inplace = True)

In [79]:
# Checking if the change is applied
data.head(3)

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   

                                                    playerUrl     Nationality  \
Joined                                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...           Japan   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...  Korea Republic   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...          Russia   

            Age  OVA  POT             Club Contract_Status Positions  \
Joined                                                                 
1998-01-01   40   65   65  Kashima Antlers          Active        GK   
2002-01-01   37   70   70  Pohang Steelers          Active        CB   
2002-01-01   34   80   80  PFC CSKA Moscow          Active        GK   

            Height_cm  Weight_kg Preferred_Foot  BOV Best_Position  \
Joined                                                               
1998-01-01        187         80          Right   65            GK   
2002-01-01        183         73          Right   70            CB   
2002-01-01        186         78          Right   80            GK   

            Value_in_Euro  Wage_in_Euro  Release_Clause_in_Euro  Attacking  \
Joined                                                                       
1998-01-01          80000          1000                   63000         87   
2002-01-01         275000          3000                  438000        260   
2002-01-01        3600000         40000                10400000         83   

            Crossing  Finishing  Heading_Accuracy  Short_Passing  Volleys  \
Joined                                                                      
1998-01-01        13         12                18             26       18   
2002-01-01        58         38                70             55       39   
2002-01-01        19         13                18             23       10   

            Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  \
Joined                                                                         
1998-01-01     84         14     10           11            33            16   
2002-01-01    232         51     46           30            49            56   
2002-01-01     91         15     19           13            22            22   

            Movement  Acceleration  Sprint_Speed  Agility  Reactions  Balance  \
Joined                                                                          
1998-01-01       143            17            19       28         47       32   
2002-01-01       325            69            61       54         73       68   
2002-01-01       270            51            50       53         71       45   

            Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
Joined                                                                  
1998-01-01    203          48       52       37        51          15   
2002-01-01    316          48       89       63        75          41   
2002-01-01    241          59       62       35        72          13   

            Mentality  Aggression  Interceptions  Positioning  Vision  \
Joined                                                                  
1998-01-01        100          21             12           10      45   
2002-01-01        285          71             73           55      43   
2002-01-01        121          24             17           

In [80]:
# Checking the unique value in the A/W column
data['A/W'].unique()

array(['Medium', 'Low', 'High'], dtype=object)

We can convert this column into a categorical type

Also we can rename it 

In [81]:
# Renaming column from A/W to AW_Rate Attack working Rate

data.rename(columns= {'A/W':'AW_Rate'}, inplace=True)

# Converting the column to a categorical type
data['AW_Rate'] = data['AW_Rate'].astype('category')

In [82]:
# Renaming column from D/W to DW_Rate, defensive work rate

data.rename(columns= {'D/W':'DW_Rate'}, inplace=True)

# Converting the column to a categorical type
data['DW_Rate'] = data['DW_Rate'].astype('category')

In [83]:
data.head(3)

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   

                                                    playerUrl     Nationality  \
Joined                                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...           Japan   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...  Korea Republic   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...          Russia   

            Age  OVA  POT             Club Contract_Status Positions  \
Joined                                                                 
1998-01-01   40   65   65  Kashima Antlers          Active        GK   
2002-01-01   37   70   70  Pohang Steelers          Active        CB   
2002-01-01   34   80   80  PFC CSKA Moscow          Active        GK   

            Height_cm  Weight_kg Preferred_Foot  BOV Best_Position  \
Joined                                                               
1998-01-01        187         80          Right   65            GK   
2002-01-01        183         73          Right   70            CB   
2002-01-01        186         78          Right   80            GK   

            Value_in_Euro  Wage_in_Euro  Release_Clause_in_Euro  Attacking  \
Joined                                                                       
1998-01-01          80000          1000                   63000         87   
2002-01-01         275000          3000                  438000        260   
2002-01-01        3600000         40000                10400000         83   

            Crossing  Finishing  Heading_Accuracy  Short_Passing  Volleys  \
Joined                                                                      
1998-01-01        13         12                18             26       18   
2002-01-01        58         38                70             55       39   
2002-01-01        19         13                18             23       10   

            Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  \
Joined                                                                         
1998-01-01     84         14     10           11            33            16   
2002-01-01    232         51     46           30            49            56   
2002-01-01     91         15     19           13            22            22   

            Movement  Acceleration  Sprint_Speed  Agility  Reactions  Balance  \
Joined                                                                          
1998-01-01       143            17            19       28         47       32   
2002-01-01       325            69            61       54         73       68   
2002-01-01       270            51            50       53         71       45   

            Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
Joined                                                                  
1998-01-01    203          48       52       37        51          15   
2002-01-01    316          48       89       63        75          41   
2002-01-01    241          59       62       35        72          13   

            Mentality  Aggression  Interceptions  Positioning  Vision  \
Joined                                                                  
1998-01-01        100          21             12           10      45   
2002-01-01        285          71             73           55      43   
2002-01-01        121          24             17           

### Cleaning the IR column

In [84]:
# Checking the unique value in the IR column
data['IR'].unique()

array(['1 ★', '3 ★', '2 ★', '5 ★', '4 ★'], dtype=object)

From observation, the IR column represent a rating, it represent the player's injury resistance ability

It can be considered as categorigal also

But we have to remove the unwanted character from it
we will be removing the star from it '★'


In [85]:
# Apply the function to IR column 
data['IR'] = data['IR'].apply(remove_star)

We may want to as well rename the column to IR_rate for better understanding

In [86]:
# Renaming column from A/W to AW_Rate Attack working Rate

data.rename(columns= {'IR':'IR_Rate'}, inplace=True)

In [87]:
# CHecking if the change is applied
data.head(3)

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   

                                                    playerUrl     Nationality  \
Joined                                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...           Japan   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...  Korea Republic   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...          Russia   

            Age  OVA  POT             Club Contract_Status Positions  \
Joined                                                                 
1998-01-01   40   65   65  Kashima Antlers          Active        GK   
2002-01-01   37   70   70  Pohang Steelers          Active        CB   
2002-01-01   34   80   80  PFC CSKA Moscow          Active        GK   

            Height_cm  Weight_kg Preferred_Foot  BOV Best_Position  \
Joined                                                               
1998-01-01        187         80          Right   65            GK   
2002-01-01        183         73          Right   70            CB   
2002-01-01        186         78          Right   80            GK   

            Value_in_Euro  Wage_in_Euro  Release_Clause_in_Euro  Attacking  \
Joined                                                                       
1998-01-01          80000          1000                   63000         87   
2002-01-01         275000          3000                  438000        260   
2002-01-01        3600000         40000                10400000         83   

            Crossing  Finishing  Heading_Accuracy  Short_Passing  Volleys  \
Joined                                                                      
1998-01-01        13         12                18             26       18   
2002-01-01        58         38                70             55       39   
2002-01-01        19         13                18             23       10   

            Skill  Dribbling  Curve  FK_Accuracy  Long_Passing  Ball_Control  \
Joined                                                                         
1998-01-01     84         14     10           11            33            16   
2002-01-01    232         51     46           30            49            56   
2002-01-01     91         15     19           13            22            22   

            Movement  Acceleration  Sprint_Speed  Agility  Reactions  Balance  \
Joined                                                                          
1998-01-01       143            17            19       28         47       32   
2002-01-01       325            69            61       54         73       68   
2002-01-01       270            51            50       53         71       45   

            Power  Shot_Power  Jumping  Stamina  Strength  Long_Shots  \
Joined                                                                  
1998-01-01    203          48       52       37        51          15   
2002-01-01    316          48       89       63        75          41   
2002-01-01    241          59       62       35        72          13   

            Mentality  Aggression  Interceptions  Positioning  Vision  \
Joined                                                                  
1998-01-01        100          21             12           10      45   
2002-01-01        285          71             73           55      43   
2002-01-01        121          24             17           

### Cleaning the Hits column

In [88]:
# Checking the unique values in the Hits column
data['Hits'].unique()

array(['1', '3', '18', '5', '2', '10', '14', '771', '35', '7', '125',
       '130', '6', '212', '4', '133', '19', '71', '11', '22', '107', '15',
       '32', '30', '9', '175', '126', '119', '42', '12', '16', '31', '20',
       '33', '216', '64', '43', nan, '28', '8', '256', '41', '75', '94',
       '332', '116', '17', '47', '138', '24', '90', '40', '13', '123',
       '23', '134', '46', '25', '194', '313', '154', '217', '29', '58',
       '52', '167', '45', '118', '36', '96', '87', '26', '65', '62', '21',
       '421', '182', '84', '86', '53', '99', '197', '145', '165', '156',
       '109', '196', '34', '27', '170', '39', '124', '141', '8.4K', '137',
       '214', '200', '89', '121', '142', '565', '169', '128', '69', '68',
       '77', '211', '85', '229', '282', '406', '38', '177', '193', '76',
       '367', '324', '50', '55', '402', '173', '220', '222', '248',
       '3.2K', '37', '88', '48', '150', '161', '102', '114', '103', '67',
       '388', '377', '239', '279', '61', '262', '93'

In [89]:
# Checking the number of null values available in the column
data['Hits'].isnull().sum()

2595

 - #### Observation 

 - From Observation, It was observed that the Hits column contains NaN value
 - The column contain an alphabetical value 'K' which represent thousand
 #### How to resolve it
  - Apply the function that will remove the 'K' and convert it by multipling with 1000,
  - also converting the values into integers
  - Filling NaN value with Zero

In [90]:
# Filling null values with "0" so that it wont affect our function

data['Hits'] = data['Hits'].fillna('0')

In [91]:
#confirming if there is still any null value left
data['Hits'].isnull().sum()

0

Now that we are sure we dont have any null values, we can now define a function
A function that will replace 'K' with an empty string
convert the values into a float and then multiply the values with K by 1000...

In [92]:
# definind a function that will remove 'K' and convert it to thousand in integers
def clean_hits(x):
    # a condition that if there is 'K' in the column
    if 'K' in x:
        # replace the 'K' with an empty string
        x = x.replace('K', '')
        # convert the column to a float and multiply it by 1000
        x = float(x) * 1000
        # return the round off value of the column
        return round(x)
    else:
        # if there is no 'K' in the column
        # convert the column into a float
        x = float(x)
        # return a round off value for the entire column
        return round(x)

We can now apply our function to the column

In [93]:
# Appling the function
data['Hits'] = data['Hits'].apply(clean_hits)

In [94]:
# Confirming if the change is applied

# This below code return the properties of the player which their Hits column value is greater 1000 hits
data[data['Hits'] > 1000]

ID             Name                       LongName  \
Joined                                                               
2013-07-01  231485      A. Tuanzebe                  Axel Tuanzebe   
2014-07-01  231677      M. Rashford                Marcus Rashford   
2016-10-24  238071      D. Sterling                 Dujon Sterling   
2017-01-13  229558     D. Upamecano                Dayot Upamecano   
2017-08-31  233049        J. Sancho                   Jadon Sancho   
2018-02-02  255611       D. Maldini                 Daniel Maldini   
2018-07-01  231747        K. Mbappé                  Kylian Mbappé   
2018-07-01  251852       K. Adeyemi                  Karim Adeyemi   
2018-07-01  253004        Ansu Fati                 Anssumane Fati   
2018-07-01  251470  C. De Ketelaere           Charles De Ketelaere   
2018-07-23  245371        T. Almada                  Thiago Almada   
2018-10-02  246147     M. Greenwood                Mason Greenwood   
2019-01-20  248243     E. Camavinga              Eduardo Camavinga   
2019-06-29  229880   A. Wan-Bissaka              Aaron Wan-Bissaka   
2019-07-03  220651         Angeliño     José Ángel Esmoris Tasende   
2019-12-07  245541         G. Reyna                 Giovanni Reyna   
2019-12-21  254796       N. Madueke                   Noni Madueke   
2020-01-01  239085       E. Haaland                 Erling Haaland   
2020-01-30  212198  Bruno Fernandes  Bruno Miguel Borges Fernandes   
2020-07-01  255475           Antony      Antony Matheus dos Santos   
2020-07-23  252371    J. Bellingham                Jude Bellingham   
2020-08-04  244778          Trincão  Francisco Mota Castro Trincão   
2020-08-04  251854            Pedri           Pedro González López   
2020-08-31  205343    J. Akpa Akpro         Jean-Daniel Akpa Akpro   
2020-10-01  251804          S. Dest                   Sergiño Dest   
2020-10-05  253283     F. Pellistri              Facundo Pellistri   
2020-10-05  212462      Alex Telles            Alex Nicolao Telles   

                                                    photoUrl  \
Joined                                                         
2013-07-01  https://cdn.sofifa.com/players/231/485/21_60.png   
2014-07-01  https://cdn.sofifa.com/players/231/677/21_60.png   
2016-10-24  https://cdn.sofifa.com/players/238/071/21_60.png   
2017-01-13  https://cdn.sofifa.com/players/229/558/21_60.png   
2017-08-31  https://cdn.sofifa.com/players/233/049/21_60.png   
2018-02-02  https://cdn.sofifa.com/players/255/611/21_60.png   
2018-07-01  https://cdn.sofifa.com/players/231/747/21_60.png   
2018-07-01  https://cdn.sofifa.com/players/251/852/21_60.png   
2018-07-01  https://cdn.sofifa.com/players/253/004/21_60.png   
2018-07-01  https://cdn.sofifa.com/players/251/470/21_60.png   
2018-07-23  https://cdn.sofifa.com/players/245/371/21_60.png   
2018-10-02  https://cdn.sofifa.com/players/246/147/21_60.png   
2019-01-20  https://cdn.sofifa.com/players/248/243/21_60.png   
2019-06-29  https://cdn.sofifa.com/players/229/880/21_60.png   
2019-07-03  https://cdn.sofifa.com/players/220/651/21_60.png   
2019-12-07  https://cdn.sofifa.com/players/245/541/21_60.png   
2019-12-21  https://cdn.sofifa.com/players/254/796/21_60.png   
2020-01-01  https://cdn.sofifa.com/players/239/085/21_60.png   
2020-01-30  https://cdn.sofifa.com/players/212/198/21_60.png   
2020-07-01  https://cdn.sofifa.com/players/255/475/21_60.png   
2020-07-23  https://cdn.sofifa.com/players/252/371/21_60.png   
2020-08-04  https://cdn.sofifa.com/players/244/778/21_60.png   
2020-08-04  https://cdn.sofifa.com/players/251/854/21_60.png   
2020-08-31  https://cdn.sofifa.com/players/205/343/21_60.png   
2020-10-01  https://cdn.sofifa.com/players/251/804/21_60.png   
2020-10-05  https://cdn.sofifa.com/players/253/283/21_60.png   
2020-10-05  https://cdn.sofifa.com/players/212/462/21_60.png   

                                                    playerUrl    Nationality  \
Joined                                          

# EDA

## Visualization

In [104]:
pd.set_option('display.max_rows', None)
data.corr()

ID       Age       OVA       POT  Height_cm  \
ID                      1.000000 -0.753413 -0.486968  0.023736  -0.108373   
Age                    -0.753413  1.000000  0.466140 -0.269473   0.090232   
OVA                    -0.486968  0.466140  1.000000  0.632166   0.033368   
POT                     0.023736 -0.269473  0.632166  1.000000  -0.009826   
Height_cm              -0.108373  0.090232  0.033368 -0.009826   1.000000   
Weight_kg              -0.209820  0.241969  0.147973 -0.024619   0.772076   
BOV                    -0.443686  0.401796  0.987149  0.669677   0.022455   
Value_in_Euro          -0.131001  0.040994  0.552893  0.528200   0.004179   
Wage_in_Euro           -0.256117  0.157751  0.589601  0.485241   0.023596   
Release_Clause_in_Euro -0.161860  0.074079  0.599142  0.548897   0.003975   
Attacking              -0.180955  0.146765  0.446337  0.284542  -0.364712   
Crossing               -0.156939  0.124639  0.406600  0.255631  -0.488562   
Finishing              -0.117892  0.081765  0.323638  0.216708  -0.372443   
Heading_Accuracy       -0.140575  0.146402  0.325182  0.179505   0.013020   
Short_Passing          -0.173973  0.142810  0.500041  0.351508  -0.352683   
Volleys                -0.189012  0.138232  0.372520  0.229958  -0.343208   
Skill                  -0.184415  0.132555  0.458098  0.314697  -0.452129   
Dribbling              -0.079190  0.024563  0.376388  0.307785  -0.480500   
Curve                  -0.196558  0.139144  0.417868  0.276144  -0.438530   
FK_Accuracy            -0.222498  0.181559  0.382736  0.213187  -0.401780   
Long_Passing           -0.220780  0.183336  0.484577  0.314743  -0.318005   
Ball_Control           -0.136157  0.091793  0.447363  0.331928  -0.411220   
Movement               -0.038604 -0.022100  0.354798  0.311086  -0.618818   
Acceleration            0.093328 -0.142046  0.203445  0.241466  -0.543916   
Sprint_Speed            0.091788 -0.135785  0.212523  0.242221  -0.461061   
Agility                -0.059803 -0.012064  0.276601  0.235622  -0.614316   
Reactions              -0.472715  0.454699  0.866954  0.509078  -0.000388   
Balance                 0.019268 -0.076881  0.126790  0.155335  -0.765199   
Power                  -0.310576  0.299444  0.572780  0.286291  -0.143947   
Shot_Power             -0.318014  0.266381  0.557946  0.334879  -0.156880   
Jumping                -0.206838  0.204923  0.283194  0.111208  -0.001952   
Stamina                -0.101355  0.118090  0.379696  0.207132  -0.284809   
Strength               -0.297844  0.348577  0.356192  0.064985   0.530854   
Long_Shots             -0.194421  0.155406  0.405656  0.241704  -0.379277   
Mentality              -0.252161  0.226098  0.499758  0.288993  -0.316762   
Aggression             -0.240876  0.244119  0.397913  0.187498  -0.044524   
Interceptions          -0.170786  0.180499  0.315541  0.158974  -0.058434   
Positioning            -0.127357  0.095557  0.352186  0.228352  -0.438813   
Vision                 -0.254340  0.196022  0.507402  0.338202  -0.361554   
Penalties              -0.170147  0.136748  0.327826  0.197405  -0.319803   
Composure              -0.412840  0.357505  0.703051  0.423777  -0.156926   
Defending              -0.109787  0.118043  0.272015  0.162243  -0.075788   
Marking                -0.156884  0.162004  0.317043  0.173577  -0.071567   
Standing_Tackle        -0.093070  0.101411  0.256152  0.158544  -0.072905   
Sliding_Tackle         -0.075177  0.085888  0.229146  0.145731  -0.078414   
Goalkeeping            -0.115777  0.121684  0.006304 -0.039022   0.368620   
GK_Diving              -0.111569  0.117085  0.005138 -0.038078   0.364673   
GK_Handling            -0.113757  0.117987  0.004731 -0.038337   0.364270   
GK_Kicking             -0.112879  0.119175  0.001663 -0.042994   0.361142   
GK_Positioning         -0.123415  0.129497  0.013473 -0.036007   0.364441   
GK_Reflexes            -0.110397  0.117392  0.006018 -0.037498   0.365756   
Total_Stats            -0.

In [ ]:
sns.boxplot(x=data['Age'])
plt.show()

In [99]:
data.Skill.unique()

array([ 84, 232,  91, 300,  89, 231, 386, 206, 101, 301, 104, 326, 263,
       256, 165, 470, 367, 246, 258, 233, 274,  92, 244, 314,  88, 290,
       276,  96, 323, 381, 297,  87, 309,  67, 281, 207, 313, 311, 107,
       271, 266,  77, 304, 408, 118, 353, 152, 273, 310, 336, 347, 260,
       344, 324, 322, 288, 319, 270, 298, 312, 368, 242, 295,  72, 254,
       221, 331, 350, 245, 340, 334, 346, 316, 151, 110, 197, 343, 205,
       341, 373,  65,  93, 325, 375, 249, 317, 415, 333, 291, 365,  83,
       315, 262, 354,  90,  76, 349, 264, 337, 283, 332, 302, 269, 366,
       404, 307, 394, 181, 117, 320, 359, 257, 237, 296, 306,  80, 376,
       321, 195, 299, 255, 236, 401, 338, 235, 213, 318, 358, 363, 103,
       228, 282,  63, 268, 124, 395, 141, 425, 303,  78, 292, 360, 225,
       285, 345, 293, 294,  94, 252, 335, 327, 409, 208, 279, 277, 289,
       189, 222, 188, 112, 265, 387, 419, 126, 377, 403, 371, 143,  75,
       220, 243, 364,  98, 355, 229, 223, 384, 261,  82, 250, 16

In [103]:
data.head()

ID           Name          LongName  \
Joined                                                
1998-01-01  140181    H. Sogahata  Hitoshi Sogahata   
2002-01-01  184900  Kim Kwang Suk     Kwang Suk Kim   
2002-01-01  148119    I. Akinfeev     Igor Akinfeev   
2002-08-01  138830   D. Lewington    Dean Lewington   
2003-01-01  142333     M. McNulty      Mark McNulty   

                                                    photoUrl  \
Joined                                                         
1998-01-01  https://cdn.sofifa.com/players/140/181/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/184/900/21_60.png   
2002-01-01  https://cdn.sofifa.com/players/148/119/21_60.png   
2002-08-01  https://cdn.sofifa.com/players/138/830/21_60.png   
2003-01-01  https://cdn.sofifa.com/players/142/333/21_60.png   

                                                    playerUrl  \
Joined                                                          
1998-01-01  http://sofifa.com/player/140181/hitoshi-sogaha...   
2002-01-01  http://sofifa.com/player/184900/kwang-suk-kim/...   
2002-01-01  http://sofifa.com/player/148119/igor-akinfeev/...   
2002-08-01  http://sofifa.com/player/138830/dean-lewington...   
2003-01-01  http://sofifa.com/player/142333/mark-mcnulty/2...   

                    Nationality  Age  OVA  POT                Club  \
Joined                                                               
1998-01-01                Japan   40   65   65     Kashima Antlers   
2002-01-01       Korea Republic   37   70   70     Pohang Steelers   
2002-01-01               Russia   34   80   80     PFC CSKA Moscow   
2002-08-01              England   36   65   65  Milton Keynes Dons   
2003-01-01  Republic of Ireland   39   60   60           Cork City   

           Contract_Status Positions  Height_cm  Weight_kg Preferred_Foot  \
Joined                                                                      
1998-01-01          Active        GK        187         80          Right   
2002-01-01          Active        CB        183         73          Right   
2002-01-01          Active        GK        186         78          Right   
2002-08-01          Active   LB, LWB        183         86           Left   
2003-01-01          Active        GK        190         70          Right   

            BOV Best_Position  Value_in_Euro  Wage_in_Euro  \
Joined                                                       
1998-01-01   65            GK          80000          1000   
2002-01-01   70            CB         275000          3000   
2002-01-01   80            GK        3600000         40000   
2002-08-01   65            LB         160000          2000   
2003-01-01   60            GK          25000           500   

            Release_Clause_in_Euro  Attacking  Crossing  Finishing  \
Joined                                                               
1998-01-01                   63000         87        13         12   
2002-01-01                  438000        260        58         38   
2002-01-01                10400000         83        19         13   
2002-08-01                  175000        229        66         22   
2003-01-01                   31000         90        16         12   

            Heading_Accuracy  Short_Passing  Volleys  Skill  Dribbling  Curve  \
Joined                                                                          
1998-01-01                18             26       18     84         14     10   
2002-01-01                70             55       39    232         51     46   
2002-01-01                18             23       10     91         15     19   
2002-08-01                58             65       18    300         54     59   
2003-01-01                12             36       14     89         12     19   

            FK_Accuracy  Long_Passing  Ball_Control  Movement  Acceleration  \
Joined                                                                        
1998-01-01           11            33     

In [ ]:
data['Age'].mean()

In [ ]:
data[data['Age']>50]

In [ ]:
sns.pairplot(data[[]])